---
apiVersion: v1
kind: Service
metadata:
  name: app-lb
  namespace: k8s-vault-dynamic-credentials
  # annotations:
  #   service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    role: app
